import csv
from datetime import datetime
from io import BytesIO, StringIO

from flask import Blueprint, Response, make_response, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from app.auth.decorators import role_required
from app.extensions import db
from app.reports.services import (
    applied_filter_labels,
    build_report,
    clean_filters,
    export_rows,
    filter_options,
)
from app.services.audit import record_audit

reports_bp = Blueprint("reports", __name__, url_prefix="/reports")


@reports_bp.route("")
@reports_bp.route("/")
@login_required
@role_required("Admin", "Encoder", "Analyst")
def index():
    filters = clean_filters(request.args)
    report = None
    if request.args.get("generated") == "1":
        report = build_report(current_user, filters)
    return render_template(
        "reports/index.html",
        filters=filters,
        filter_options=filter_options(current_user),
        report=report,
    )


@reports_bp.route("/summary")
@login_required
@role_required("Admin", "Encoder", "Analyst")
def summary():
    filters = clean_filters(request.args)
    report = build_report(current_user, filters)
    record_audit(
        "generate",
        "reports",
        remarks=f"Generated {report['title']}.",
        new_values=_audit_payload(filters, report["title"], "preview"),
    )
    db.session.commit()
    query = _query_with_generated(filters)
    return redirect(url_for("reports.index", **query))


@reports_bp.route("/export/excel")
@login_required
@role_required("Admin", "Encoder", "Analyst")
def export_excel():
    filters = clean_filters(request.args)
    report = build_report(current_user, filters)
    _record_export(filters, report["title"], "excel")

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Report"
    sheet.append(["Lifeline Sentinel"])
    sheet.append([report["title"]])
    sheet.append([f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"])
    sheet.append([f"Generated by: {current_user.full_name} ({current_user.role})"])
    sheet.append(["Applied filters", ", ".join(f"{label}: {value}" for label, value in applied_filter_labels(filters)) or "None"])
    sheet.append([])
    for item in report["summary"]:
        sheet.append([item["label"], item["value"]])
    sheet.append([])
    sheet.append(report["columns"])
    for row in export_rows(report):
        sheet.append(row)

    header_row = sheet.max_row - len(export_rows(report))
    for cell in sheet[header_row]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="0F766E")
    for column_cells in sheet.columns:
        width = max(len(str(cell.value or "")) for cell in column_cells) + 2
        sheet.column_dimensions[column_cells[0].column_letter].width = min(width, 45)

    buffer = BytesIO()
    workbook.save(buffer)
    buffer.seek(0)
    response = make_response(buffer.read())
    response.headers["Content-Type"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    response.headers["Content-Disposition"] = f"attachment; filename={_filename(filters, 'xlsx')}"
    return response


@reports_bp.route("/export/csv")
@login_required
@role_required("Admin", "Encoder", "Analyst")
def export_csv():
    filters = clean_filters(request.args)
    report = build_report(current_user, filters)
    _record_export(filters, report["title"], "csv")

    output = StringIO()
    writer = csv.writer(output)
    writer.writerow(["Lifeline Sentinel"])
    writer.writerow([report["title"]])
    writer.writerow([f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"])
    writer.writerow([f"Generated by: {current_user.full_name} ({current_user.role})"])
    writer.writerow([])
    writer.writerow(report["columns"])
    writer.writerows(export_rows(report))
    return Response(
        output.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": f"attachment; filename={_filename(filters, 'csv')}"},
    )


def _record_export(filters, title, export_format):
    record_audit(
        "export",
        "reports",
        remarks=f"Exported {title} as {export_format.upper()}.",
        new_values=_audit_payload(filters, title, export_format),
    )
    db.session.commit()


def _audit_payload(filters, title, export_format):
    return {
        "report_name": "registry_entries",
        "report_title": title,
        "user_id": current_user.id,
        "role": current_user.role,
        "timestamp": datetime.utcnow().isoformat(),
        "filters": {key: value.isoformat() if hasattr(value, "isoformat") else value for key, value in filters.items()},
        "export_format": export_format,
    }


def _query_with_generated(filters):
    query = {key: value.isoformat() if hasattr(value, "isoformat") else value for key, value in filters.items() if value}
    query["generated"] = "1"
    return query


def _filename(filters, extension):
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    return f"lifeline-sentinel-registry-entries-{stamp}.{extension}"
