"""update psychiatric history dictionary fields

Revision ID: 4c31ffb063fd
Revises: 559332ba6139
Create Date: 2026-05-16 23:14:41.071319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c31ffb063fd'
down_revision = '559332ba6139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatric_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substance_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatric_histories', schema=None) as batch_op:
        batch_op.drop_column('substance_details')

    # ### end Alembic commands ###
