"""implement phase 3 registry module

Revision ID: 559332ba6139
Revises: e8f4a1c2d9b7
Create Date: 2026-05-16 22:48:23.850467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559332ba6139'
down_revision = 'e8f4a1c2d9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_code', sa.String(length=50), nullable=False),
    sa.Column('data_steward_code', sa.String(length=50), nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('date_of_presentation', sa.Date(), nullable=False),
    sa.Column('time_of_presentation', sa.Time(), nullable=True),
    sa.Column('reporting_department', sa.Enum('ER', 'OPS'), nullable=False),
    sa.Column('is_valid_registry_case', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=255), nullable=True),
    sa.Column('patient_identifier', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex_at_birth', sa.String(length=50), nullable=False),
    sa.Column('sexual_orientation', sa.String(length=100), nullable=True),
    sa.Column('sexual_orientation_other', sa.String(length=150), nullable=True),
    sa.Column('gender_identity', sa.String(length=100), nullable=True),
    sa.Column('gender_identity_other', sa.String(length=150), nullable=True),
    sa.Column('marital_status', sa.String(length=100), nullable=True),
    sa.Column('highest_educational_attainment', sa.String(length=150), nullable=True),
    sa.Column('employment_status', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('religion_other', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_code')
    )
    op.create_table('case_ascertainments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('Intentional', 'Accidental'), nullable=False),
    sa.Column('infliction', sa.Enum('Self-inflicted', 'Inflicted by another'), nullable=False),
    sa.Column('type_of_consult', sa.String(length=100), nullable=False),
    sa.Column('type_of_consult_other', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('primary_diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('secondary_diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('disposition', sa.String(length=150), nullable=True),
    sa.Column('disposition_other', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('is_first_incident', sa.Boolean(), nullable=False),
    sa.Column('has_past_2_month_incident', sa.Boolean(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_day', sa.String(length=20), nullable=True),
    sa.Column('incident_time_period', sa.String(length=50), nullable=True),
    sa.Column('incident_place', sa.String(length=150), nullable=True),
    sa.Column('incident_place_other', sa.String(length=150), nullable=True),
    sa.Column('incident_region', sa.String(length=100), nullable=True),
    sa.Column('incident_province_city', sa.String(length=100), nullable=True),
    sa.Column('incident_municipality', sa.String(length=100), nullable=True),
    sa.Column('self_poisoning_methods', sa.JSON(), nullable=True),
    sa.Column('self_harm_methods', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychiatric_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('previous_consultation', sa.Boolean(), nullable=True),
    sa.Column('previous_consultation_notes', sa.Text(), nullable=True),
    sa.Column('family_history', sa.Boolean(), nullable=True),
    sa.Column('family_history_notes', sa.Text(), nullable=True),
    sa.Column('friends_history', sa.Boolean(), nullable=True),
    sa.Column('friends_history_notes', sa.Text(), nullable=True),
    sa.Column('substance_use', sa.Boolean(), nullable=True),
    sa.Column('substances', sa.JSON(), nullable=True),
    sa.Column('substance_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psychiatric_histories')
    op.drop_table('incident_details')
    op.drop_table('diagnosis_dispositions')
    op.drop_table('case_ascertainments')
    op.drop_table('registries')
    # ### end Alembic commands ###
